Repository mju-likelion/antigua, pull requests merged in 2021-02, with the labels that each got.

#15 Refactor User List API for Pagination
  src/api/auth/auth.ctrl.ts
Labels: ☕️ 개발, 🛠 리팩터링

#16 Refactor login, logout system
  src/api/auth/auth.ctrl.ts
  src/api/auth/index.ts
  src/lib/jwtMiddleware.ts
Labels: ☕️ 개발, 👥 회원관리, 🛠 리팩터링

#18 Apply Docker
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: ☕️ 개발, 🤖 기능
